[package]
name = "itag2mqttd"
version = "0.1.0"
edition = "2021"

[dependencies]
bluer = { version = "0.17.1", features = ["bluetoothd"] }
configparser = "3.1.0"
rumqttc = "0.24.0"
tokio = { version = "1.38.0", features = ["tokio-macros", "rt"] }
tokio-stream = "0.1.15"
